spring.application.name=salusLaboris
server.port=8080

# Conexión MySQL Workbench (root@localhost:3306)
spring.datasource.url=jdbc:mysql://localhost:3306/salus_laboris?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate (Las tablas ya están creadas en tu Workbench)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

# Seguridad JWT
app.jwt.secret-base64=c2FsdXNsYWJvcmlzc2VjdXJpdHlrZXkyMDI2dmVyeXNlY3JldGFuZHZlcnlsb25nMTIzNDU2Nzg5MDEyMzQ1Ng==
app.jwt.expiration-ms=3600000
app.jwt.issuer=salus-laboris-api


# CORS (Frontend Angular)
app.cors.allowed-origins=http://localhost:4200

# Bootstrap en FALSE porque ya insertaste los datos a mano en MySQL
app.bootstrap.enabled=false

# Políticas de Error
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never